# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe8\x80\x85\xe5\xa7\x93\xe5\x90\x8d')),
                ('user_email', models.CharField(max_length=100, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('user_phone', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
                ('user_grade', models.CharField(max_length=30, verbose_name=b'\xe5\xb9\xb4\xe7\xba\xa7')),
                ('user_messages', models.CharField(max_length=255, verbose_name=b'\xe7\x95\x99\xe8\xa8\x80')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe8\xaf\x84\xe8\xae\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
    ]
